# yaml-language-server: $schema=../../task.yaml.schema.json

name: powershell
command: "aaa"

description: "Install different softwares using chocolatey"
author: "jiakou@microsoft.com"
documentationURL: "https://docs.chocolatey.org/en-us/choco/commands/install"
licenseURL: "..."
keywords: ['choco', 'chocolatey', 'install']
timeout: 20
inputs:
  package:
      type: string
      description: "Specify the package to install using chocolatey"
      allowedValues: ['vscode', 'notepadplusplus.install']
      defaultValue: ""
      required: true
  version:
      type: string
      description: "Specify the version of the package"
      defaultValue: ""
      required: true
